title: Cillian Frawley
logo: https://media.licdn.com/dms/image/v2/D4E03AQEi844SWSTr0w/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1712425028730?e=1741824000&v=beta&t=r8X7gD5usGJD4MLUV2w3keSmOCi1jdgCW9slLclH3aU
description: My portfolio
#show_download: true
theme: jekyll-theme-minimal
